name: Build & Test PR to develop branch

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: |
          bun install

      - name: lint
        run: bun lint:check

      - name: Test
        run: bun run test

      - name: Build Project
        run: bun run build
